"""Add media support to posts

Revision ID: cd61adc760de
Revises: 90687ad6ce8a
Create Date: 2025-11-07 23:19:48.131420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd61adc760de'
down_revision = '90687ad6ce8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
