"""Add profile image and partners count to users

Revision ID: f5a78e754c8a
Revises: cd61adc760de
Create Date: 2025-11-07 23:48:32.097167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a78e754c8a'
down_revision = 'cd61adc760de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('partners_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('partners_count')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###